SET SERVEROUTPUT ON
DECLARE
    PUNTAJE_MAXIMO NUMBER:= 20;
    PUNTAJE_LOGRADO NUMBER;
    FACTOR NUMBER;
    NOTA NUMBER;
BEGIN
    FOR PUNTAJE_LOGRADO IN 0..PUNTAJE_MAXIMO
    LOOP
     FACTOR:=PUNTAJE_LOGRADO/PUNTAJE_MAXIMO;
     IF (FACTOR>=0.6) THEN
        NOTA:=ROUND(FACTOR*7.5-0.5,1);
        DBMS_OUTPUT.PUT_LINE('PARA EL PUNTAJE '||PUNTAJE_LOGRADO||'LA NOTA ES: '||NOTA);
     ELSE
        NOTA:=ROUND(FACTOR*5+1,1);
        DBMS_OUTPUT.PUT_LINE('PARA EL PUNTAJE '||PUNTAJE_LOGRADO||'LA NOTA ES: '||NOTA);
     END IF;
    END LOOP;
END;