SET SERVEROUTPUT ON
DECLARE
    NUMERO NUMBER:=109;
    COPIA_NUM NUMBER:=NUMERO;
    POTENCIA NUMBER:=1;
    SUMA NUMBER:=0;
BEGIN
    LOOP
        EXIT WHEN COPIA_NUM<10;
        POTENCIA:=POTENCIA*10;
        COPIA_NUM:=TRUNC(COPIA_NUM/10);
    END LOOP;
    COPIA_NUM:=NUMERO;
    LOOP
        EXIT WHEN COPIA_NUM<10;
        SUMA:=SUMA+MOD(COPIA_NUM,10)*POTENCIA;
        POTENCIA:=TRUNC(POTENCIA/10);
        COPIA_NUM:=TRUNC(COPIA_NUM/10);
    END LOOP;
    SUMA:=SUMA+COPIA_NUM*POTENCIA;
    DBMS_OUTPUT.PUT_LINE('EL NUMERO '||NUMERO||' AL INVERTIRLO QUEDA COMO '||SUMA);
END;
