SET SERVEROUTPUT ON
DECLARE
    NUMERO_POSITIVO NUMBER:=123;
    SUMA_DIGITOS NUMBER:= 0;
BEGIN
    NUMERO_POSITIVO:=ABS(NUMERO_POSITIVO);
    WHILE (NUMERO_POSITIVO >=10)
    LOOP
        SUMA_DIGITOS:=SUMA_DIGITOS+MOD(NUMERO_POSITIVO,10);
        NUMERO_POSITIVO:=TRUNC(NUMERO_POSITIVO/10);
    END LOOP;
    SUMA_DIGITOS:=SUMA_DIGITOS+NUMERO_POSITIVO;
    DBMS_OUTPUT.PUT_LINE('LA SUMA DE DIGITOS ES: '||SUMA_DIGITOS);
END;