SET SERVEROUTPUT ON
DECLARE
    FECHA_NACIMIENTO DATE:=TO_DATE('27-09-1980');
    EDAD NUMBER:= 0;
BEGIN
    EDAD:=TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12);
    DBMS_OUTPUT.PUT_LINE('LA EDAD DE LA PERSONA ES: '||EDAD);
END;