SET SERVEROUTPUT ON
DECLARE
    PUNTAJE_MAXIMO_PRUEBA NUMBER:=100;
    PUNTAJE_OBTENIDO_PRUEBA NUMBER:=75;
    FACTOR_LOGRO NUMBER;
    NOTA_OBTENIDA NUMBER;
BEGIN
    /*CALCULO DE NOTAUSANDO ESCALA DE 60%*/
    FACTOR_LOGRO:=PUNTAJE_OBTENIDO_PRUEBA/PUNTAJE_MAXIMO_PRUEBA;
    /*ESTRUCTURA DE CONTROL IF THEN ELSE*/
    IF (FACTOR_LOGRO>=0.6) THEN
        NOTA_OBTENIDA:=FACTOR_LOGRO*7.5-0.5;
    ELSE
        NOTA_OBTENIDA:=ROUND(FACTOR_LOGRO*5+1);
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('LA NOTA OBTENIDA ES: '||NOTA_OBTENIDA);

END;