SET SERVEROUTPUT ON
DECLARE
    NOMBRE VARCHAR2(50);
    SUELDO NUMBER;
    FECHA_NACIMIENTO DATE;
    RESPUESTA BOOLEAN;
BEGIN
    /*EL OPERADOR DE ASIGNACION EN ORACLE ES := */
    NOMBRE:='INACAP';
    SUELDO:=750000;
    FECHA_NACIMIENTO:=TO_DATE('06-11-2010');
    RESPUESTA:=TRUE;
    /*PARA MOSTRAR POR CONSOLA EL RESULTADO DE LAS VARIABLES, SE USA LA INSTRUCCION
    DBMS_OUTPUT.PUT_LINE(VARIABLE)*/
    DBMS_OUTPUT.PUT_LINE(NOMBRE);
    DBMS_OUTPUT.PUT_LINE('EL CONTENIDO DE LA VARIABLE SUELDO ES: '||SUELDO);
    DBMS_OUTPUT.PUT_LINE('LA FECHA DE NACIMIENTO ES: '||FECHA_NACIMIENTO);
    DBMS_OUTPUT.PUT_LINE('EL VALOR DE LA VARIABLE RESPUESTA ES: '||CASE WHEN RESPUESTA THEN 'TRUE' ELSE 'FALSE' END);
END;