CREATE TABLE DICCIONARIO(
CODIGO NUMBER,
CARACTER VARCHAR2(1),
CONSTRAINT DICCIONARIO_PK PRIMARY KEY(CODIGO));

INSERT INTO DICCIONARIO VALUES(1,'_');
INSERT INTO DICCIONARIO VALUES(2,'@');
INSERT INTO DICCIONARIO VALUES(3,'-');
INSERT INTO DICCIONARIO VALUES(4,'.');
INSERT INTO DICCIONARIO VALUES(5,':');
INSERT INTO DICCIONARIO VALUES(6,';');
INSERT INTO DICCIONARIO VALUES(7,',');
INSERT INTO DICCIONARIO VALUES(8,' ');
INSERT INTO DICCIONARIO VALUES(9,'(');
INSERT INTO DICCIONARIO VALUES(10,')');
INSERT INTO DICCIONARIO VALUES(11,'/');
INSERT INTO DICCIONARIO VALUES(12,'&');
INSERT INTO DICCIONARIO VALUES(13,'?');
INSERT INTO DICCIONARIO VALUES(14,'=');
INSERT INTO DICCIONARIO VALUES(15,'%');
INSERT INTO DICCIONARIO VALUES(16,'¿');
INSERT INTO DICCIONARIO VALUES(17,'¡');
INSERT INTO DICCIONARIO VALUES(18,'!');
INSERT INTO DICCIONARIO VALUES(19,'|');
INSERT INTO DICCIONARIO VALUES(20,'+');
INSERT INTO DICCIONARIO VALUES(21,'*');
INSERT INTO DICCIONARIO VALUES(22,'{');
INSERT INTO DICCIONARIO VALUES(23,'}');
INSERT INTO DICCIONARIO VALUES(24,'[');
INSERT INTO DICCIONARIO VALUES(25,']');
INSERT INTO DICCIONARIO VALUES(26,'>');
INSERT INTO DICCIONARIO VALUES(27,'<');
INSERT INTO DICCIONARIO VALUES(28,'#');
INSERT INTO DICCIONARIO VALUES(29,'$');
INSERT INTO DICCIONARIO VALUES(30,'"');
