--EJERCICIO 1 GUIA
CREATE OR REPLACE FUNCTION TEXTO_ANTES_TEXTO_DESPUES(TEXTO VARCHAR2, CAD VARCHAR2)
RETURN VARCHAR2
IS
    RESPUESTA VARCHAR2(200):='';
    COPIA_TXT VARCHAR2(200) := TEXTO;
    I NUMBER;
    LETRA VARCHAR(1):='';
BEGIN
     COPIA_TXT:=REPLACE(COPIA_TXT,CAD,'#');
     FOR I IN 1..LENGTH(COPIA_TXT)
     LOOP
        LETRA:=SUBSTR(COPIA_TXT,I,1);
        IF(LETRA!='#')THEN
            RESPUESTA:=RESPUESTA||LETRA;
        END IF;
    END LOOP;
    RETURN RESPUESTA;
END;