CREATE OR REPLACE FUNCTION MOSTRAR_PK
RETURN VARCHAR2
IS
    SALIDA VARCHAR2(100):='';
    PK_MINIMA NUMBER;
    PK_MAXIMA NUMBER;CUENTA NUMBER;
    PK NUMBER; 
BEGIN
    SELECT MIN(CODIGO), MAX(CODIGO) INTO PK_MINIMA,PK_MAXIMA FROM PAIS;
    /*SELECT MAX(CODIGO) INTO PK_MAXIMA FROM PAIS;*/
    FOR PK IN PK_MINIMA..PK_MAXIMA
    LOOP
        SELECT COUNT(*) INTO CUENTA FROM PAIS WHERE CODIGO=PK;
        IF (CUENTA=0) THEN
            SALIDA:=SALIDA||TO_CHAR(PK);
        END IF;
    END LOOP;
    RETURN SALIDA;
END;