/*UNIDAD 3: PLSQL EN ORACLE
BLOQUES ANONIMOS, FUNCIONES, PROCEDIMIENTOS Y DISPARADORES*/

/*BLOQUES ANONIMOS SON ENTIDADES DE CODIGO QUE NO SE ALMACENAN COMO OBJETOS DE LA BASE DE DATOS
PERO SE USAN PARA AUTOMATIZAR CIERTAS TAREAS Y SIRVEN PARA INVOCAR A FUNCIONES, PROCEDIMIENTOS 
Y DISPARADORES. POR MEDIO DE UN BLOQUE ANONIMO SE PUEDE VISULAIZAR LA CONSOLA DE ORACLE CON LA
CUAL SE PUEDEN COMPROBAR RESULTADOS*/

/* EN UN BLOQUE ANONIMO, DESTACAN LAS SIGUIENTES INSTRUCCIONES:*/

SET SERVEROUTPUT ON /*ACTIVA LA CONSOLA DE ORACLE*/
DECLARE /*SE USA PARA DECLARAR VARIABLES*/

BEGIN/*INICIO DEL BLOQUE ANONIMO*/
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO'); /*INSTRUCCION PARA ESCRIBIR EN LA CONSOLA*/
END; /* FINAL DEL BLOQUE ANONIMO*/