CREATE TABLE PRODUCTO(
CODIGO NUMBER,
NOMBRE VARCHAR2(70),
PRECIO NUMBER,
STOCK NUMBER,
FECHA_FABRICACION DATE,
CONSTRAINT PRO_PK PRIMARY KEY(CODIGO));

DESCRIBE PRODUCTO;

CREATE TABLE PROYECTO(
CODIGO NUMBER,
NOMBRE VARCHAR(70) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE NOT NULL,
PRESUPUESTO NUMBER NOT NULL,
CONSTRAINT PROYECTO_PK PRIMARY KEY(CODIGO));

DESCRIBE PROYECTO;
-- COMENTARIO DE UNA SOLA LINEA
/* COMENTARIO DE MAS DE
UNA LINEA*/

-- EJEMPLO DE UNA TABLA CON CLAVE PRIMARIA COMPUESTA
CREATE TABLE DETALLE_VENTA(
COD_VENTA NUMBER,
COD_PRODUCTO NUMBER,
CANTIDAD NUMBER,
TOTAL_PARCIAL NUMBER,
CONSTRAINT DETALLE_PK PRIMARY KEY (COD_VENTA,COD_PRODUCTO));
-- DROP TABLE ELIMINA UNA TABLA CON DATOS Y ESTRUCTURA
DROP TABLE PROYECTO;

DESCRIBE PROYECTO;

DROP TABLE DETALLE_VENTA;
-- TRUNCATE TABLE ELIMINA EL CONTENIDO DE LA TABLA SIN AFECTAR SU ESTRUCTURA
TRUNCATE TABLE PRODUCTO;
-- ALTER TABLE PERMITE MODIFICAR LA ESTRUCTURA DE UNA TABLA
-- ADD PERMITE AÑADIR UNA NUEVA COLUMNA
ALTER TABLE PRODUCTO ADD MARCA VARCHAR2(70);
ALTER TABLE PRODUCTO ADD PESO NUMBER;
-- DROP COLUMN ELIMINA UNA COLUMNA
ALTER TABLE PRODUCTO DROP COLUMN PESO;
--RENAME COLUMN RENOMBRA UNA COLUMNA 
ALTER TABLE PRODUCTO RENAME COLUMN PRECIO TO VALOR;
ALTER TABLE PRODUCTO RENAME COLUMN FECHA_FABRICACION TO FECHA_ELABORACION;
-- MODIFY CAMBIA EL TIPO DE DATO PARA UNA COLUMNA
ALTER TABLE PRODUCTO MODIFY STOCK VARCHAR2(50);
ALTER TABLE PRODUCTO MODIFY MARCA VARCHAR2(100);
DESCRIBE PRODUCTO;
CREATE TABLE REGION(
NUMERO NUMBER,
NOMBRE VARCHAR2(70),
SUPERFICIE NUMBER,
CONSTRAINT REG_PK PRIMARY KEY(NUMERO));
CREATE TABLE COMUNA(
CODIGO NUMBER,
NOMBRE VARCHAR2(70) NOT NULL,
TOTAL_POBLACION NUMBER,
COD_REGION NUMBER,
CONSTRAINT COMUNA_PK PRIMARY KEY(CODIGO),
-- ESTE CODIGO SE USA PARA CREAR CLAVES FORANEAS
CONSTRAINT COMUNA_02_FK FOREIGN KEY(COD_REGION) REFERENCES REGION(NUMERO));
-- INGRESAR DATOS EN UNA TABLA
INSERT INTO REGION (NUMERO,NOMBRE,SUPERFICIE) VALUES (7,'DEL MAULE',123);
-- PARA SELECCIONAR FILAS DENTRO DE UNA TABLA
SELECT * FROM REGION;
-- TAMBIEN SE PUEDEN OMITIR LOS VALORES DELA TABLA CON EL COMANDO VALUES
INSERT INTO REGION VALUES (8,'BIO BIO',259);
INSERT INTO REGION VALUES (9,'DE LA ARAUCANIA',450);
SELECT * FROM REGION;
INSERT INTO COMUNA VALUES (1,'CURICO',80000,7);
SELECT * FROM COMUNA;
INSERT INTO COMUNA VALUES (82,'TALCA',120000,7);
SELECT * FROM COMUNA;
INSERT INTO COMUNA VALUES (3,'CONCEPCION',220000,8);
DESCRIBE REGION;
DESCRIBE COMUNA;
INSERT INTO PRODUCTO VALUES (1,'NOTEBOOK',350000,'10','10-10-2022','LENOVO');
INSERT INTO PRODUCTO VALUES (2,'MOUSE','','','','DELL');
INSERT INTO PRODUCTO VALUES (3,'TECLADO',NULL,'20',NULL,'GENIUS');
INSERT INTO PRODUCTO (CODIGO,NOMBRE,MARCA) VALUES (4,'IMPRESORA','HP');
--UPDATE SIRVE PARA ACTUALIZAR DATOS DENTRO DE UNA TABLA
UPDATE PRODUCTO
SET VALOR=400000
WHERE NOMBRE='NOTEBOOK';
SELECT * FROM PRODUCTO;
INSERT INTO PRODUCTO VALUES (5,'NOTEBOOK',550000,'6','10-10-2022','SAMSUNG');
--INCREMENTAR EL STOCK DE LOS NOTEBOOKS EN 5 UNIDADES
UPDATE PRODUCTO
SET STOCK=STOCK+5
WHERE NOMBRE='NOTEBOOK';
SELECT * FROM PRODUCTO;
-- MODIFICAR STOCK NULL A '10'
UPDATE PRODUCTO
SET STOCK='10'
WHERE STOCK IS NULL;
SELECT * FROM PRODUCTO;
-- MODIFICAR LA COLUMNA VALOR  CON LA CIFRA 10000 CUANDO  ES NULL
UPDATE PRODUCTO
SET VALOR='10000'
WHERE VALOR IS NULL;
SELECT * FROM PRODUCTO;
-- MODIFICAR LA COLUMNA FECHA_ELABORACION CON LA FECHA ACTUAL CUANDO ES NULO
UPDATE PRODUCTO
SET FECHA_ELABORACION='22-05-2024'--SE PUEDE USAR TAMBIEN LA FUNCION SYSDATE PARA QUE EL EDITOR LA CAPTURE AUTOMATICAMENTE.
WHERE FECHA_ELABORACION IS NULL;
SELECT * FROM PRODUCTO;
--DELETE SIRVE PARA BORRAR ELEMENTOS DE UNA TABLA
DELETE FROM PRODUCTO
WHERE NOMBRE='NOTEBOOK';
SELECT * FROM PRODUCTO;
DELETE FROM PRODUCTO;
-- ELIMINE LAREGION CON NOMBRE 'BIO BIO'
SELECT * FROM REGION;
DELETE FROM REGION
WHERE NOMBRE='BIO BIO';
SELECT * FROM COMUNA;
-- ELIMINE LA 'REGION DE LA ARAUCANIA'
DELETE FROM REGION
WHERE NOMBRE='DE LA ARAUCANIA';
--ELIMINE LA COMUNA CON NOMBRE 'CURICO'
DELETE FROM COMUNA
WHERE NOMBRE='CURICO';
--AGREGAR LA COLUMNA CAPITAL_REGION DE TIPO VARCHAR2(70) EN LA TABLA REGION
ALTER TABLE REGION ADD CAPITAL_REGION VARCHAR2(70);
SELECT * FROM REGION;
UPDATE REGION
SET CAPITAL_REGION='TALCA'
WHERE NUMERO=7;
UPDATE REGION
SET CAPITAL_REGION='CONCEPCION'
WHERE NUMERO=8;
SELECT * FROM REGION;